services:
  - type: web
    name: puppeteer-api
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node index.js
    branch: main
    region: oregon
